# yaml-language-server: $schema=https://raw.githubusercontent.com/kometa-team/kometa/nightly/json-schema/config-schema.json
## Do not remove the above line
## This file is a template remove the .template to use the file

## Plex and TMDb are the two connections which are required for the script to run

plex:                              # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.0.20:32400/   # Enter Plex URL (REQUIRED); this needs to point to your server, not app.plex.tv
  token: -5RJ9zWdH8pHLLXK5won      # Enter Plex Token (REQUIRED)
  timeout: 60
  db_cache: 1024
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: true
tmdb:
  apikey: 21370118bc9b23713002ebbc3168a3f9                         # Enter TMDb API Key (REQUIRED)
  cache_expiration: 60
  language: en
  region:

libraries:                         # This is called out once within the config.yml file
  Movies:                                           # Must match a library name in your Plex
    report_path: config/missing/Movies_report.yml
    remove_overlays: false                          # Set to true if you want to remove overlays
    reapply_overlays: false                         # Before setting this to true, you should know what you are doing and open a #kometa-help beforehand
    template_variables:
      sep_style: gray                               # use the gray separators globally for this library
      collection_mode: hide                         # hide the collections
      language: en                                  # could be default(which is en), da, de, fr, pt-br or another lang code that we have translated
      placeholder_imdb_id: tt8579674                # 1917 (2019) placeholder id for the separators
    collection_files:                               # These files contain collections: and/or dynamic_collections attributes
    - git: bullmoose20/movies_refresh               # tells plex to refresh media items added within the last 7 days
    - file: /config/collections/seasonal.yml
    - file: /config/collections/raunchy_comedy.yml
    - default: oscars                               # The Oscars
      template_variables:                           # based on when the award show started
        use_year_collections: false
        data:
          starting: first
    - default: separator_chart                      # An "index card"
    - default: imdb                                 # IMDb Charts (Popular, Trending, etc.)
    - default: tmdb                                 # TMDb Charts (Popular, Trending, etc.)
    - default: basic                                # Some basic chart collections based on recently released media in your library
    - default: collectionless                       # Collectionless collection to help Show/Hide Movies/Shows properly in your library
    - default: genre                                # Action, Comedy, Drama, etc.
    - default: studio                               # DreamWorks Studios, Lucasfilm Ltd, etc.
    - git: bullmoose20/separator_franchise          # Separator for franchise
      template_variables:
        collection_section: '035'                   # Set to "035" to be right before universe. Should be the same here and below
    - default: franchise                            # https://kometa.wiki/en/latest/defaults/movie/franchise
      template_variables:
        collection_section: '035'                   # Set to "035" to be right before universe. Should be the same here and above
    - default: streaming                            # Streaming on Disney+, Netflix, etc.
      template_variables:
        originals_only: true
    - default: universe                             # Marvel Cinematic Universe, Wizarding World, etc.
# .--------------------------------------------------------.
# | _     _ _        ___                 _                 |
# || |   (_) |__    / _ \__   _____ _ __| | __ _ _   _ ___ |
# || |   | | '_ \  | | | \ \ / / _ \ '__| |/ _` | | | / __||
# || |___| | |_) | | |_| |\ V /  __/ |  | | (_| | |_| \__ \|
# ||_____|_|_.__/   \___/  \_/ \___|_|  |_|\__,_|\__, |___/|
# |                                              |___/     |
# '--------------------------------------------------------'
    overlay_files:                                  # These files contain overlays: attributes
    - default: audio_codec                          # FLAC, DTS-X, TrueHD, etc. style: standard/compact. compact is default
      template_variables:
        # Enable only Atmos variants
        use_truehd_atmos: true
        use_dolby_atmos: true
        use_plus_atmos: true

        # Disable all other supported audio codecs
        use_dtsx: false
        use_truehd: false
        use_ma: false
        use_flac: false
        use_pcm: false
        use_hra: false
        use_plus: false
        use_dtses: false
        use_dts: false
        use_digital: false
        use_aac: false
        use_mp3: false
        use_opus: false

    # - default: direct_play                          # Show direct play only overlay
    - default: mediastinger                         # Mediastinger overlay when the media item contains a stinger at the end of the movie/show or during the credits
      template_variables:
        vertical_align: top
        horizontal_align: right
    - default: ratings                              # Ratings with custom fonts matched to the style of the rating, font_size, and on the right in 'square' format
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/metadata/overlays/fonts/Impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating3_font_size: 70

        horizontal_position: left
        vertical_position: bottom
        vertical_offset: 15

        # rating_source: Anidb
        # font: config/metadata/overlays/fonts/Handel Gothic ITC W01 Heavy.ttf
        # rating_source: IMDb
        # font: config/metadata/overlays/fonts/Impact.ttf
        # rating_source: Letterboxd
        # font: config/metadata/overlays/fonts/HelveticaNowDisplay-ExtBlk.ttf
        # rating_source: Metacritic
        # font: config/metadata/overlays/fonts/Myriad Bold.otf
        # rating_source: TMDb
        # font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        # rating_source: Trakt
        # font: config/metadata/overlays/fonts/Claspo-ND-Medium.ttf
        # rating_source: Rotten
        # font: config/metadata/overlays/fonts/Adlib.ttf
    - default: ribbon                               # Used for ribbon in bottom right
      template_variables:
        use_all: false    # turn them all off
        use_oscars: true  # then turn a few back on
        use_oscars_director: true
        use_emmys: true
        style: black
    - default: streaming                               # DreamWorks Studios, Lucasfilm Ltd, etc.
      template_variables:
        originals_only: true
        horizontal_align: right
        #horizontal_offset: 20%
        vertical_align: bottom
        #vertical_offset: 11% 
#    - default: versions                             # Will show duplicates for that media item and works with builder_level show, episode, and season
      # template_variables:
        # back_color: "#f5289180"
        # vertical_offset: 0
        # horizontal_offset: 0
        # back_width: 2000
        # back_height: 3000
    - default: resolution                         # Remux, DVD, Blu-Ray, etc. in bottom left
      template_variables:
        use_edition: true
        # Enable only these (4K HDR/DV variants)
        use_4k_hdr: true
        use_4k_dv: true
        use_4k_dvhdr: true
        use_4k_dvhdrplus: true
        use_4k_plus: true  # HDR10+
        use_4k: false

        # Disable all 1080p variants
        use_1080p: false
        use_1080p_hdr: false
        use_1080p_dv: false
        use_1080p_dvhdr: false
        use_1080p_dvhdrplus: false
        use_1080p_plus: false

        # Disable all 720p variants
        use_720p: false
        use_720p_hdr: false
        use_720p_dv: false
        use_720p_dvhdr: false
        use_720p_dvhdrplus: false
        use_720p_plus: false

        # Disable all 576p variants
        use_576p: false
        use_576p_hdr: false
        use_576p_dv: false
        use_576p_dvhdr: false
        use_576p_dvhdrplus: false
        use_576p_plus: false

        # Disable all 480p variants
        use_480p: false
        use_480p_hdr: false
        use_480p_dv: false
        use_480p_dvhdr: false
        use_480p_dvhdrplus: false
        use_480p_plus: false

        # Disable all SD/other legacy variants
        use_sd: false
        use_sd_hdr: false
        use_sd_dv: false
        use_sd_dvhdr: false
        use_sd_dvhdrplus: false
        use_sd_plus: false
# .------------------------------------------------------.
# | _     _ _       ____       _   _   _                 |
# || |   (_) |__   / ___|  ___| |_| |_(_)_ __   __ _ ___ |
# || |   | | '_ \  \___ \ / _ \ __| __| | '_ \ / _` / __||
# || |___| | |_) |  ___) |  __/ |_| |_| | | | | (_| \__ \|
# ||_____|_|_.__/  |____/ \___|\__|\__|_|_| |_|\__, |___/|
# |                                            |___/     |
# '------------------------------------------------------'
    settings:
      asset_directory: config/assets/Movies/
      prioritize_assets: true                       # The asset_directory contains folders per media item with respective posters
# .------------------------------------------------------------------.
# | _     _ _        ___                       _   _                 |
# || |   (_) |__    / _ \ _ __   ___ _ __ __ _| |_(_) ___  _ __  ___ |
# || |   | | '_ \  | | | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __||
# || |___| | |_) | | |_| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \|
# ||_____|_|_.__/   \___/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/|
# |                      |_|                                         |
# '------------------------------------------------------------------'
    operations:
      split_duplicates: false                       # Splits all duplicate movies/shows found in this library
      assets_for_all: true                          # Search in assets for images for every item in your library
      delete_collections:
        configured: false                           # False - Collection must be an Unconfigured Collection to be deleted (collection is not in the config file of the specific Kometa run).
        managed: false                              # False - Collection must be an Unmanaged Collection to be deleted (the collection does not have the Kometa label)
        less: 99999                                 # Effectively all collections regardless of teh number of items in the collection
      mass_user_rating_update: mdb_tomatoesaudience         # Update user ratings with mdb_tomatoes
      mass_critic_rating_update: imdb               # Update critic ratings with imdb
      mass_audience_rating_update: tmdb             # Update audience ratings with tmdb
      mass_genre_update:
      - tmdb                                        # Update all genres from tmdb
      - imdb                                        # Update all genres from imdb if not from tmdb
      - tvdb                                        # Update all genres from tvdb if not from imdb
      mass_content_rating_update:
      - mdb_commonsense                             # Changes Content Rating to "1", "2" etc. to specify appropriate age
      - omdb                                        # Changes Content Rating from omdb if not found on mdb_commonsense
      mass_studio_update:
      - tmdb                                        # Update all studios from tmdb
      mass_originally_available_update:
      - tmdb                                        # Update all original available date from tmdb
      - tvdb                                        # Update all original available date from tvdb if not from tmdb
      - omdb                                        # Update all original available date from omdb(imdb) if not from tvdb
      mass_imdb_parental_labels: none               # Apply all Parental Labels with a value of None, Mild, Moderate, or Severe to match IMDb parental guide
      # mass_poster_update: tmdb                      # Resets posters to tmdb, plex, locked, unlock which is useful to remove all overlays when running with -r -op

#  TV Shows:
#    remove_overlays: false         # Set this to true to remove all overlays
#    collection_files:
#    - default: basic               # This is a file within Kometa's defaults folder
#    - default: imdb                # This is a file within Kometa's defaults folder
                                   # see the wiki for how to use local files, folders, URLs, or files from git
#    overlay_files:
#    - default: ribbon              # This is a file within Kometa's defaults folder
                                   # see the wiki for how to use local files, folders, URLs, or files from git
#  Anime:
#    collection_files:
#      - default: basic             # This is a file within Kometa's defaults folder
#      - default: anilist           # This is a file within Kometa's defaults folder
                                   # see the wiki for how to use local files, folders, URLs, or files from git
#  Music:
#    collection_files:
#      - file: config/Music.yml     # This is a local file THAT YOU MIGHT CREATE
#playlist_files:
#  - default: playlist              # This is a file within Kometa's defaults folder
#    template_variables:
#      libraries: Movies, TV Shows  # list of libraries that you want the Kometa Defaults playlists to look at
                                   # see the wiki for how to use local files, folders, URLs, or files from git
settings:
  run_order:
  - operations
  - metadata
  - overlays
  - collections
  cache: true
  cache_expiration: 60
  asset_directory:
  - config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_unfiltered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users:
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: webp_lossy
  overlay_artwork_quality: 90
webhooks:                          # Can be individually specified per library as well
  changes:
  delete:
  error:
  run_end:
  run_start:
  version:
tautulli:                          # Can be individually specified per library as well
  url: http://192.168.1.12:8181    # Enter Tautulli URL (Optional)
  apikey:                          # Enter Tautulli API Key (Optional)
github:
  token:                           # Enter GitHub Personal Access Token (Optional)
omdb:
  apikey:                          # Enter OMDb API Key (Optional)
  cache_expiration: 60
mdblist:
  apikey: iu4too000ay5w9d0frrdd0kut                         # Enter MDBList API Key (Optional)
  cache_expiration: 60
notifiarr:
  apikey:                          # Enter Notifiarr API Key (Optional)
gotify:
  url: http://192.168.1.12:80      # Enter Gotify server URL (Optional)
  token:                           # Enter Gotify Token (Optional)
ntfy:
  url: http://192.168.1.12:80      # Enter ntfy server URL (Optional)
  token:                           # Enter ntfy Access Token (Optional)
  topic:                           # Enter ntfy Topic (Optional)
anidb:                             # Not required for AniDB builders unless you want mature content
  username:                        # Enter AniDB Username (Optional)
  password:                        # Enter AniDB Password (Optional)
  cache_expiration: 60
  client:                          # Enter AniDB Client (Optional)
  language: en
  version: 1
radarr:                            # Can be individually specified per library as well
  url: http://192.168.0.30:7878    # Enter Radarr server URL (Optional)
  token: 8319c83bad94438b9411aa4b3c37688e                          # Enter Radarr API Key (Optional)
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: /data/media/movies    # This value is CASE SENSITIVE
  monitor: true
  availability: released
  quality_profile: "Remux 2160p (Alternative)"        # This value is CASE SENSITIVE
  tag: kometa
  search: false
  radarr_path:                    # This value is only needed in combination with the *_existing settings
  plex_path:                      # This value is only needed in combination with the *_existing settings
  ignore_cache: false
sonarr:                            # Can be individually specified per library as well
  url: http://192.168.1.12:8989    # Enter Sonarr server URL (Optional)
  token:                           # Enter Sonarr API Key (Optional)
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: "S:/TV Shows"  # This value is CASE SENSITIVE
  monitor: all
  quality_profile: "Remux 2160p (Alternative)"        # This value is CASE SENSITIVE
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:                     # This value is only needed in combination with the *_existing settings
  plex_path:                       # This value is only needed in combination with the *_existing settings
  ignore_cache: false
trakt:
  client_id:                       # Enter Trakt Client ID (Optional)
  client_secret:                   # Enter Trakt Client Secret (Optional)
  pin:
  authorization:
                                   # authorization section is autofilled by the script
    access_token:
    created_at:
    expires_in:
    refresh_token:
    scope: public
    token_type:
mal:
  client_id:                       # Enter MyAnimeList Client ID (Optional)
  client_secret:                   # Enter MyAnimeList Client Secret (Optional)
  cache_expiration: 60
  localhost_url:
  authorization:
                                   # authorization section is autofilled by the script
    access_token:
    expires_in:
    refresh_token:
    token_type:
